name: Preview Deploy

on:
  pull_request:
    branches:
      - main
      - uat
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Application
        run: npm run build
        env:
          NODE_ENV: production
        
      - name: Deploy Preview to Vercel
        id: deploy
        run: |
          # Install Vercel CLI
          npm install -g vercel@latest
          
          # Remove any existing .vercel directory
          rm -rf .vercel
          
          # Deploy preview (not production)
          DEPLOYMENT_URL=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --yes)
          echo "Preview URL: $DEPLOYMENT_URL"
          echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          
      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;
            const deployment_url = '${{ steps.deploy.outputs.url }}';
            
            const comment = `
            ## 🚀 Preview Deployment Ready!
            
            **Preview URL:** ${deployment_url}
            
            This preview was automatically generated for this pull request.
            `;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr_number,
              body: comment
            });
